name: Deploy to AKS
on: 
  workflow_dispatch:
      inputs:
        resource-group:
          description: 'resource group name'     
#           required: true
          default: 'tx-rg-aks'
        aks-service-name:
          description: 'Test scenario tags'
          default: 'tx-aks'

env:
  GROUP: ${{ github.event.inputs.resource-group }}
  SERVICE_NAME: ${{ github.event.inputs.aks-service-name }}
  CLUSETER_NAME: tx-aks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

#     - name: maven build, clean
#       run: |
#         mvn clean package -DskipTests
# "Azure Spring Cloud Prod Test v3 - TTL = 1 Days" - 6c933f90-8115-4392-90f2-7077c9fa5dbd
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_AKS }}
        
    - name: Deploy
      run: |
        echo "resource group: ${{ github.event.inputs.resource-group }}"
        echo "aks service name: ${{ github.event.inputs.aks-service-name }}"
        az account set -s 6c933f90-8115-4392-90f2-7077c9fa5dbd 
        az config set defaults.group=$GROUP
        az config set defaults.spring-cloud=$SERVICE_NAME
        
        az group create --name $GROUP --location eastus2
        az aks create --resource-group $GROUP --name $SERVICE_NAME --node-count 1 --enable-addons monitoring --generate-ssh-keys
