name: Deploy to AKS
on: [workflow_dispatch]

env:
  GROUP: tx-rg-aks
  SERVICE_NAME: taoxu-ask-test
  CLUSETER_NAME: tx-aks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: maven build, clean
      run: |
        mvn clean package -DskipTests

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy
      run: |
      
        az account set -s f86578d4-0e67-40ef-9073-c43a7ebbb49b  
        az config set defaults.group=$GROUP
        az config set defaults.spring-cloud=$SERVICE_NAME
        
        az group create --name $GROUP --location eastus2
        az aks create --resource-group $GROUP --name $SERVICE_NAME --node-count 1 --enable-addons monitoring --generate-ssh-keys
