name: Deploy to ASC Enterprise tier
on: 
  workflow_dispatch:
      inputs:
        resource-group:
          description: 'resource group name'     
#           required: true
          default: 'tx-rg'
        service-name:
          description: 'asc service name'
          default: 'tx-asc'

env:
  GROUP: ${{ github.event.inputs.resource-group }}
  SERVICE_NAME: ${{ github.event.inputs.service-name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: maven build, clean
      run: |
        mvn clean package -DskipTests

    - name: Azure Login
      uses: azure/login@v1
      with:
      # "Azure Spring Cloud Prod Test v3 - TTL = 1 Days" - 6c933f90-8115-4392-90f2-7077c9fa5dbd
      # az ad sp create-for-rbac --role contributor --scopes /subscriptions/6c933f90-8115-4392-90f2-7077c9fa5dbd --sdk-auth
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Install ASC extension
      run: |
        az extension add -s https://ascprivatecli.blob.core.windows.net/enterprise/spring_cloud-2.7.0a1-py3-none-any.whl -y

# need create ASC instance and resource group head. 
    - name: Deploy
      run: |
        # Azure Spring Cloud Prod Test v3 - TTL = 1 Days
        az account set -s 6c933f90-8115-4392-90f2-7077c9fa5dbd  
        az config set defaults.group=$GROUP
        az config set defaults.spring-cloud=$SERVICE_NAME 
        
        
        az spring-cloud app deploy -n vets-service --jar-path ${{ github.workspace }}/spring-petclinic-vets-service/target/spring-petclinic-vets-service-2.3.6.jar --config-file-patterns "vets-service"
        az spring-cloud app deploy -n visits-service --jar-path ${{ github.workspace }}/spring-petclinic-visits-service/target/spring-petclinic-visits-service-2.3.6.jar --config-file-patterns "visits-service"
